### ISSUE TITLE
Cannot instantiate OgcWmsHarvester (throws TypeError)

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/nexus-geonode#375]
As soon as I hit Save for a new OgcWmsHarvester I get the following exception:

```
Internal Server Error: /en/admin/harvesting/harvester/add/
Traceback (most recent call last):
  File "/home/giohappy/miniconda3/envs/nexus-geonode/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/giohappy/miniconda3/envs/nexus-geonode/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/giohappy/miniconda3/envs/nexus-geonode/lib/python3.8/site-packages/django/contrib/admin/options.py", line 616, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/giohappy/miniconda3/envs/nexus-geonode/lib/python3.8/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/giohappy/miniconda3/envs/nexus-geonode/lib/python3.8/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/giohappy/miniconda3/envs/nexus-geonode/lib/python3.8/site-packages/django/contrib/admin/sites.py", line 232, in inner
    return view(request, *args, **kwargs)
  File "/home/giohappy/miniconda3/envs/nexus-geonode/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1657, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "/home/giohappy/miniconda3/envs/nexus-geonode/lib/python3.8/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/giohappy/miniconda3/envs/nexus-geonode/lib/python3.8/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/giohappy/miniconda3/envs/nexus-geonode/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1540, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "/home/giohappy/miniconda3/envs/nexus-geonode/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1586, in _changeform_view
    self.save_model(request, new_object, form, not add)
  File "/home/giohappy/dev/nexus/nexus-geonode/lib/geonode/geonode/harvesting/admin.py", line 79, in save_model
    available = utils.update_harvester_availability(obj)
  File "/home/giohappy/dev/nexus/nexus-geonode/lib/geonode/geonode/harvesting/utils.py", line 39, in update_harvester_availability
    worker = harvester.get_harvester_worker()
  File "/home/giohappy/dev/nexus/nexus-geonode/lib/geonode/geonode/harvesting/models.py", line 219, in get_harvester_worker
    return worker_class.from_django_record(self)
  File "/home/giohappy/dev/nexus/nexus-geonode/lib/geonode/geonode/harvesting/harvesters/wms.py", line 62, in from_django_record
    return cls(
TypeError: Can't instantiate abstract class OgcWmsHarvester with abstract methods get_geonode_resource_type
"POST /en/admin/harvesting/harvester/add/ HTTP/1.1" 500 214366
```

**Comment by meomancer** [comment]
i think this is fixed
https://github.com/GeoNode/geonode/blob/master/geonode/harvesting/harvesters/wms.py#L138

can we close this ticket @ricardogsilva @giohappy ?

**Comment by ricardogsilva** [comment]
yes, it seems to not be relevant anymore, thanks for looking into it @meomancer
