### ISSUE TITLE
Export throws Geoserver exception

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/nexus-geonode#592]
Export of vector data (as shapefile in this example) returns the following exception:

```
<?xml version="1.0" encoding="UTF-8"?><ows:ExceptionReport xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:ows="http://www.opengis.net/ows" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.0.0" xsi:schemaLocation="http://www.opengis.net/ows https://geoserver.pacificdata.org/schemas/ows/1.0.0/owsExceptionReport.xsd">
	<ows:Exception exceptionCode="InvalidParameterValue" locator="service">
		<ows:ExceptionText>No service: ( ows )</ows:ExceptionText>
	</ows:Exception>
</ows:ExceptionReport>
```

How to replicate:

1. open [https://nexus.pacificdata.org/catalogue/#/dataset/5985](https://nexus.pacificdata.org/catalogue/#/dataset/5985)
2. click export
3. select the shapefile format
4. the result panel shows the error

![image](https://user-images.githubusercontent.com/571129/170446717-c10095b4-7e55-42fc-a62d-b1bb9ee6d5ed.png)

**Comment by afabiani** [comment]
That seems to me a client issue, by following the requests I can download the file without issues

![image](https://user-images.githubusercontent.com/1278021/170456592-636d1f8e-6ab2-441e-9f3b-d2e4566b55bb.png)

![image](https://user-images.githubusercontent.com/1278021/170456611-17994d88-7794-4c1d-822d-8c43c46569cc.png)

![image](https://user-images.githubusercontent.com/1278021/170456654-2e08b56e-a5a6-4ca4-93d4-cc79c40a41d3.png)

**Comment by giohappy** [comment]
@afabiani so what? There must be some difference in the headers in that case. Please investigate a bit more.

**Comment by afabiani** [comment]
@giohappy while doing some tests I was able to rise up the log level and get this... currently GeoServer is not able to login anymore and I can't see the layers either.

```
2022-05-26 10:11:54,176 DEBUG [security.IncludeQueryStringAntPathRequestMatcher] - Checking match of request : 'Path: /ows, QueryString: service=WPS&version=1.0.0&REQUEST=GetExecutionStatus&executionId=5f76152a-eaa2-4773-bcf9-09e30f28e4cb'; against '/web/**'
2022-05-26 10:11:54,177 DEBUG [security.IncludeQueryStringAntPathRequestMatcher] - Checking match of request : 'Path: /ows, QueryString: service=WPS&version=1.0.0&REQUEST=GetExecutionStatus&executionId=5f76152a-eaa2-4773-bcf9-09e30f28e4cb'; against '/gwc/rest/web/**'
2022-05-26 10:11:54,177 DEBUG [security.IncludeQueryStringAntPathRequestMatcher] - Checking match of request : 'Path: /ows, QueryString: service=WPS&version=1.0.0&REQUEST=GetExecutionStatus&executionId=5f76152a-eaa2-4773-bcf9-09e30f28e4cb'; against '/'
2022-05-26 10:11:54,177 DEBUG [security.IncludeQueryStringAntPathRequestMatcher] - Checking match of request : 'Path: /ows, QueryString: service=WPS&version=1.0.0&REQUEST=GetExecutionStatus&executionId=5f76152a-eaa2-4773-bcf9-09e30f28e4cb'; against '/j_spring_security_check'
2022-05-26 10:11:54,177 DEBUG [security.IncludeQueryStringAntPathRequestMatcher] - Checking match of request : 'Path: /ows, QueryString: service=WPS&version=1.0.0&REQUEST=GetExecutionStatus&executionId=5f76152a-eaa2-4773-bcf9-09e30f28e4cb'; against '/j_spring_security_check/'
2022-05-26 10:11:54,177 DEBUG [security.IncludeQueryStringAntPathRequestMatcher] - Checking match of request : 'Path: /ows, QueryString: service=WPS&version=1.0.0&REQUEST=GetExecutionStatus&executionId=5f76152a-eaa2-4773-bcf9-09e30f28e4cb'; against '/j_spring_oauth2_geonode_login'
2022-05-26 10:11:54,177 DEBUG [security.IncludeQueryStringAntPathRequestMatcher] - Checking match of request : 'Path: /ows, QueryString: service=WPS&version=1.0.0&REQUEST=GetExecutionStatus&executionId=5f76152a-eaa2-4773-bcf9-09e30f28e4cb'; against '/j_spring_oauth2_geonode_login/'
2022-05-26 10:11:54,177 DEBUG [security.IncludeQueryStringAntPathRequestMatcher] - Checking match of request : 'Path: /ows, QueryString: service=WPS&version=1.0.0&REQUEST=GetExecutionStatus&executionId=5f76152a-eaa2-4773-bcf9-09e30f28e4cb'; against '/j_spring_security_logout'
2022-05-26 10:11:54,177 DEBUG [security.IncludeQueryStringAntPathRequestMatcher] - Checking match of request : 'Path: /ows, QueryString: service=WPS&version=1.0.0&REQUEST=GetExecutionStatus&executionId=5f76152a-eaa2-4773-bcf9-09e30f28e4cb'; against '/j_spring_security_logout/'
2022-05-26 10:11:54,177 DEBUG [security.IncludeQueryStringAntPathRequestMatcher] - Checking match of request : 'Path: /ows, QueryString: service=WPS&version=1.0.0&REQUEST=GetExecutionStatus&executionId=5f76152a-eaa2-4773-bcf9-09e30f28e4cb'; against '/j_spring_oauth2_geonode_logout'
2022-05-26 10:11:54,177 DEBUG [security.IncludeQueryStringAntPathRequestMatcher] - Checking match of request : 'Path: /ows, QueryString: service=WPS&version=1.0.0&REQUEST=GetExecutionStatus&executionId=5f76152a-eaa2-4773-bcf9-09e30f28e4cb'; against '/j_spring_oauth2_geonode_logout/'
2022-05-26 10:11:54,177 DEBUG [security.IncludeQueryStringAntPathRequestMatcher] - Checking match of request : 'Path: /ows, QueryString: service=WPS&version=1.0.0&REQUEST=GetExecutionStatus&executionId=5f76152a-eaa2-4773-bcf9-09e30f28e4cb'; against '/rest/geofence/**'
2022-05-26 10:11:54,177 DEBUG [security.IncludeQueryStringAntPathRequestMatcher] - Checking match of request : 'Path: /ows, QueryString: service=WPS&version=1.0.0&REQUEST=GetExecutionStatus&executionId=5f76152a-eaa2-4773-bcf9-09e30f28e4cb'; against '/rest/**'
2022-05-26 10:11:54,177 DEBUG [security.IncludeQueryStringAntPathRequestMatcher] - Checking match of request : 'Path: /ows, QueryString: service=WPS&version=1.0.0&REQUEST=GetExecutionStatus&executionId=5f76152a-eaa2-4773-bcf9-09e30f28e4cb'; against '/gwc/**'
2022-05-26 10:11:54,177 DEBUG [security.IncludeQueryStringAntPathRequestMatcher] - Checking match of request : 'Path: /ows, QueryString: service=WPS&version=1.0.0&REQUEST=GetExecutionStatus&executionId=5f76152a-eaa2-4773-bcf9-09e30f28e4cb'; against '/geofence/**'
2022-05-26 10:11:54,177 DEBUG [security.IncludeQueryStringAntPathRequestMatcher] - Checking match of request : 'Path: /ows, QueryString: service=WPS&version=1.0.0&REQUEST=GetExecutionStatus&executionId=5f76152a-eaa2-4773-bcf9-09e30f28e4cb'; against '/**'
2022-05-26 10:11:54,177 DEBUG [security.IncludeQueryStringAntPathRequestMatcher] - Request matched by universal pattern '/**'
2022-05-26 10:11:54,177 DEBUG [security.IncludeQueryStringAntPathRequestMatcher] - Matched Path: /ows, QueryString: service=WPS&version=1.0.0&REQUEST=GetExecutionStatus&executionId=5f76152a-eaa2-4773-bcf9-09e30f28e4cb with /**
2022-05-26 10:11:54,210 DEBUG [geoserver.security] - Inspecting the http request looking for the Custom Session ID.
2022-05-26 10:11:54,210 DEBUG [geoserver.security] - Found 7 cookies!
2022-05-26 10:11:54,210 DEBUG [geoserver.security] - Found Custom Session cookie: iq0uerepxq15waqxyco36ffj05saqspe
2022-05-26 10:11:54,210 DEBUG [geoserver.security] - preAuthenticatedPrincipal = null, trying to authenticate
2022-05-26 10:11:54,210 DEBUG [geoserver.monitor] - Testing /ows for monitor filtering
2022-05-26 10:11:54,213 TRACE [ows.OWSHandlerMapping] - Mapped to HandlerExecutionChain with [org.geoserver.ows.Dispatcher@47d58dec] and 2 interceptors
2022-05-26 10:11:54,214 ERROR [geoserver.ows] - 
org.geoserver.platform.ServiceException: No service: ( ows )
	at org.geoserver.ows.Dispatcher.service(Dispatcher.java:567)
	at org.geoserver.ows.Dispatcher.handleRequestInternal(Dispatcher.java:248)
	at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:177)
	at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:52)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1043)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:626)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.geoserver.filters.ThreadLocalsCleanupFilter.doFilter(ThreadLocalsCleanupFilter.java:28)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.geoserver.filters.SpringDelegatingFilter$Chain.doFilter(SpringDelegatingFilter.java:73)
	at org.geoserver.flow.controller.IpBlacklistFilter.doFilter(IpBlacklistFilter.java:89)
	at org.geoserver.filters.SpringDelegatingFilter$Chain.doFilter(SpringDelegatingFilter.java:70)
	at org.geoserver.monitor.MonitorFilter.doFilter(MonitorFilter.java:144)
	at org.geoserver.filters.SpringDelegatingFilter$Chain.doFilter(SpringDelegatingFilter.java:70)
	at org.geoserver.ows.HTTPHeadersCollector.doFilter(HTTPHeadersCollector.java:48)
	at org.geoserver.filters.SpringDelegatingFilter$Chain.doFilter(SpringDelegatingFilter.java:70)
	at org.geoserver.filters.SpringDelegatingFilter.doFilter(SpringDelegatingFilter.java:43)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.geoserver.platform.AdvancedDispatchFilter.doFilter(AdvancedDispatchFilter.java:39)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:320)
	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:71)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:127)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91)
	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:75)
	at org.geoserver.security.filter.GeoServerCompositeFilter.doFilter(GeoServerCompositeFilter.java:92)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:71)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:119)
	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:75)
	at org.geoserver.security.filter.GeoServerCompositeFilter.doFilter(GeoServerCompositeFilter.java:92)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.geoserver.security.filter.GeoServerAnonymousAuthenticationFilter.doFilter(GeoServerAnonymousAuthenticationFilter.java:53)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.geoserver.security.oauth2.GeoServerOAuthAuthenticationFilter.doFilter(GeoServerOAuthAuthenticationFilter.java:165)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:71)
	at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilterInternal(BasicAuthenticationFilter.java:158)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:75)
	at org.geoserver.security.filter.GeoServerCompositeFilter.doFilter(GeoServerCompositeFilter.java:92)
	at org.geoserver.security.filter.GeoServerBasicAuthenticationFilter.doFilter(GeoServerBasicAuthenticationFilter.java:81)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:71)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
	at org.geoserver.security.filter.GeoServerSecurityContextPersistenceFilter$1.doFilter(GeoServerSecurityContextPersistenceFilter.java:52)
	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:75)
	at org.geoserver.security.filter.GeoServerCompositeFilter.doFilter(GeoServerCompositeFilter.java:92)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178)
	at org.geoserver.security.GeoServerSecurityFilterChainProxy.doFilter(GeoServerSecurityFilterChainProxy.java:142)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:358)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:271)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.geoserver.filters.LoggingFilter.doFilter(LoggingFilter.java:102)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.geoserver.filters.GZIPFilter.doFilter(GZIPFilter.java:48)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.geoserver.filters.SessionDebugFilter.doFilter(SessionDebugFilter.java:49)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.geoserver.filters.FlushSafeFilter.doFilter(FlushSafeFilter.java:42)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:346)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:887)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1684)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by giohappy** [comment]
@afabiani any idea of what might cause it? I never saw it before.

**Comment by afabiani** [comment]
@giohappy no idea currently
